-- AlterTable
ALTER TABLE `account` ADD COLUMN `birthdate` DATE NULL,
    ADD COLUMN `code` LONGTEXT NULL,
    ADD COLUMN `display_name` LONGTEXT NULL,
    ADD COLUMN `document` LONGTEXT NULL,
    ADD COLUMN `faculty_en` LONGTEXT NULL,
    ADD COLUMN `faculty_th` LONGTEXT NULL,
    ADD COLUMN `first_name_en` LONGTEXT NULL,
    ADD COLUMN `first_name_th` LONGTEXT NULL,
    ADD COLUMN `ignored_account` DATETIME(0) NULL,
    ADD COLUMN `last_name_en` LONGTEXT NULL,
    ADD COLUMN `last_name_th` LONGTEXT NULL,
    ADD COLUMN `major_en` LONGTEXT NULL,
    ADD COLUMN `major_th` LONGTEXT NULL,
    ADD COLUMN `middle_name_en` LONGTEXT NULL,
    ADD COLUMN `middle_name_th` LONGTEXT NULL,
    ADD COLUMN `nickname_en` LONGTEXT NULL,
    ADD COLUMN `nickname_th` LONGTEXT NULL,
    ADD COLUMN `phone_number` LONGTEXT NULL,
    ADD COLUMN `point` BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN `prefix_en` LONGTEXT NULL,
    ADD COLUMN `prefix_th` LONGTEXT NULL,
    ADD COLUMN `profile_image` LONGTEXT NULL,
    ADD COLUMN `remaining_time` DATETIME(0) NULL,
    ADD COLUMN `role` ENUM('MEMBER', 'CERTIFIED') NOT NULL DEFAULT 'MEMBER',
    ADD COLUMN `status` ENUM('ORDINARY', 'PENDING', 'CERTIFIED', 'BANNED', 'ALUMNI') NOT NULL DEFAULT 'ORDINARY',
    ADD COLUMN `student_id` LONGTEXT NULL,
    ADD COLUMN `wrong_password` BIGINT NOT NULL DEFAULT 0;
