export const faculty = [
  {
    id: 1,
    th: "คณะวิทยาการจัดการ",
    en: "Faculty of Management Sciences",
    departments: [
      {
        id: 1,
        th: "การเงิน",
        en: "Finance",
        regular: "R01",
        special: "R09",
      },
      {
        id: 2,
        th: "การจัดการ",
        en: "Management",
        regular: "R02",
        special: "R08",
      },
      {
        id: 3,
        th: "การตลาด",
        en: "Marketing",
        regular: "R03",
        special: "R11",
      },
      {
        id: 4,
        th: "ธุรกิจระหว่างประเทศ",
        en: "International Business",
        regular: "R04",
        special: "R07",
      },
      {
        id: 5,
        th: "การจัดการโรงแรมและท่องเที่ยว",
        en: "Hotel and Tourism Management",
        regular: "R05",
        special: "R10",
      },
      {
        id: 6,
        th: "การโรงแรม",
        en: "Hotel Studies",
        regular: "R06",
        special: "",
      },
      {
        id: 7,
        th: "การบัญชีบริหาร",
        en: "Managerial Accounting",
        regular: "R13",
        special: "R12",
      },
      {
        id: 8,
        th: "การจัดการโลจิสติกส์",
        en: "Logistics Management",
        regular: "R14",
        special: "R15",
      },
      {
        id: 9,
        th: "การเงินและการลงทุน",
        en: "Finance and Investment",
        regular: "R16",
        special: "R17",
      },
      {
        id: 10,
        th: "จัดการโรงแรม",
        en: "Hotel Management",
        regular: "R20",
        special: "R21",
      },
      {
        id: 11,
        th: "การจัดการการท่องเที่ยวร่วมสมัย",
        en: "Contemporary Tourism Management",
        regular: "R22",
        special: "R23",
      },
      {
        id: 12,
        th: "การบัญชี",
        en: "Accounting",
        regular: "R24",
        special: "R25",
      },
      {
        id: 13,
        th: "การตลาดดิจิทัลและการสร้างตรา",
        en: "Digital Marketing and Branding",
        regular: "R32",
        special: "R33",
      },
    ],
  },
  {
    id: 2,
    th: "คณะวิศวกรรมศาสตร์ ศรีราชา",
    en: "Faculty of Engineering at Sriracha",
    departments: [
      { id: 1, th: "วิศวกรรมคอมพิวเตอร์", en: "Computer Engineering" },
    ],
  },
  {
    id: 3,
    th: "คณะวิทยาศาสตร์ ศรีราชา",
    en: "Faculty of Science at Sriracha",
    departments: [{ id: 1, th: "วิทยาการคอมพิวเตอร์", en: "Computer Science" }],
  },
  {
    id: 4,
    th: "คณะเศรษฐศาสตร์ ศรีราชา",
    en: "Faculty of Economics at Sriracha",
    departments: [{ id: 1, th: "เศรษฐศาสตร์", en: "Economics" }],
  },
  {
    id: 5,
    th: "คณะพาณิชยนาวีนานาชาติ",
    en: "Faculty of International Maritime Studies",
    departments: [
      {
        id: 1,
        th: "วิศวกรรมต่อเรือและเครื่องกลเรือ",
        en: "Naval Architecture and Marine Engineering",
      },
    ],
  },
];
